# -*- coding: utf-8 -*-
"""q1_telemetry_satyam_tripathi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4EuI4CbU-prNRgXcghDXKY6sOdsBtmP
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

import json

data = []
for line in open('/content/CRS-16.json', 'r'):
    data.append(json.loads(line))

data=pd.json_normalize(data)

data

data['velocity'].unique()

data['altitude'].unique().sum()

plt.figure(figsize=(12,8))
sns.distplot(data['altitude'])
plt.title("Distribution Of altitude",fontsize=20)

"""#Obseravtion
1-altitude is very high in the range of 200-210

2-altitude has the second high range between 0-10

3-between 10-200 altitude is having almost same value
"""

plt.figure(figsize=(12,8))
sns.distplot(data['velocity'])
plt.title("Distribution Of Velocity",fontsize=20)

"""#Obseravtion
1-Velocity is having a high value between 0-400

2-Velocity is also high between the range of 1500-2000

3-after 500 velocity is decreasing till 1500

4-after almost 2000 velocity is continuously decreasing

#Relationship between velocity and altitude
"""

plt.figure(figsize=(12,8))
sns.scatterplot(x=data['velocity'],y=data['altitude'])
plt.title("Relationship Between Velocity and Altitude",fontsize=20)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.ylabel("Altitude",fontsize=15)
plt.xlabel("Velocity",fontsize=15)

"""#Obseravtion
1-As the altitude is increasing the velocity is also increasing 

2-Same as the velocity will increase the altitude is going to increase

3-As when the altitude was 65 the velocity increased by 0-1800 approx but after reaching the 65 value on altitude the altitude is increasing very fast 

4-And after 4000 velocity no matter if we are increasing the velocity it is not crossing the altitude value of 200

#Calculating acceleration
"""

data['acceleration']=data['velocity']/data['time']

data

"""#Time vs acceleration"""

plt.figure(figsize=(12,8))
sns.scatterplot(y=data['time'],x=data['acceleration'])

"""#Obseravtion
1-as the acceleration is increasing the time is also increasing

2-For the acceleration value 0-11.7 the time taken is 150 

3-after the acceleration value of 11.7 there is a slight curve that is showing the time in increasing but the acceleration decreasing

4-after decreasing the value of acceleration when it is again reaching to the same value the time taken is high

#Time Vs Velocity Relation
"""

plt.figure(figsize=(12,8))
sns.scatterplot(y=data['time'],x=data['velocity'])

"""#Observation
1-as the time increasing the velocity is also increasing or i can say as the velocity is increasing the time is increasing

2-there is a strong relationship between time and velocity

#Rate of change
"""

data['rate of change']=data['altitude']/data['time']*100

data

"""#Rate of change vs velocity"""

plt.figure(figsize=(15,8))
plt.subplot(1,2,1)
sns.distplot(data['rate of change'])
plt.subplot(1,2,2)
sns.distplot(data['velocity'])
plt.tight_layout()

"""#Obseravtion
1-there is a reverse relationship between upper two graphs like in velocity it is first increasing and then decreasing

2-and in rate of change it is increasing from a low value
"""